spring.application.name=kafka
management.endpoints.web.exposure.include=*

# Kafka broker address - replace with your Kafka server IP (e.g. via: wsl hostname -I)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=tp-kafka-step1

# Topic
kafka.topic.name=mon-tunnel-topic
