# ============================================================
#  test.conf - Test basique stdin → stdout
#  ============================================================
#
#  Lancement :
#  logstash -f /usr/share/logstash/tp-config/test.conf --path.data test
#
#  Puis taper du texte et observer l'enrichissement automatique.
# ============================================================

input {
    stdin {}
}

output {
    stdout { codec => rubydebug }
}
